apiVersion: v1
kind: ResourceQuota
metadata:
  name: platform-demo-quota
  namespace: platform-demo
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "30"
    services: "10"
    secrets: "20"
    configmaps: "20"
