apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: platform-demo
  labels:
    platform.example.com/contract: object-storage
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: replace-with-external-secret
  AWS_SECRET_ACCESS_KEY: replace-with-external-secret
