apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-demo-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: platform-demo-app
  template:
    metadata:
      labels:
        app: platform-demo-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: TENANT_NAME
              value: {{ .Values.platform.tenantName | quote }}
            - name: OIDC_ISSUER_URL
              value: {{ .Values.platform.oidcIssuerUrl | quote }}
            - name: POSTGRES_HOST
              value: {{ .Values.platform.postgresHost | quote }}
            - name: S3_ENDPOINT
              value: {{ .Values.platform.s3Endpoint | quote }}
            - name: OTEL_ENDPOINT
              value: {{ .Values.platform.otelEndpoint | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
