apiVersion: v1
kind: Service
metadata:
  name: platform-demo-app
  labels:
    app.kubernetes.io/name: platform-demo-app
spec:
  selector:
    app.kubernetes.io/name: platform-demo-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
