apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tenant-info.yaml
  - postgres-connection.yaml
  - s3-config.yaml
  - oidc-config.yaml
  - trust-bundle.yaml
  - observability-config.yaml
