apiVersion: v1
kind: Secret
metadata:
  name: postgres-connection
  namespace: platform-demo
type: Opaque
stringData:
  PGHOST: postgres.platform-data.svc.cluster.local
  PGPORT: "5432"
  PGDATABASE: appdb
  PGUSER: appuser
  PGPASSWORD: replace-with-external-secret
