apiVersion: v1
kind: ConfigMap
metadata:
  name: tenant-info
  namespace: platform-demo
data:
  TENANT_NAME: enterprise-demo
  ENVIRONMENT: prod-like
  REGION: primary
  PLATFORM_OWNER: platform-engineering
